# Generated by Django 5.0.1 on 2024-02-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='modelos',
            new_name='modelo',
        ),
    ]
